---
dependencies:
  app_lang_selector: ^0.0.3
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  package_info_plus: ^8.0.0
  riverpod_annotation: ^2.6.1
  riverpod_helper: ^0.0.3
description: A Flutter package template.
dev_dependencies:
  auto_exporter: any
  build_runner: ^2.0.0
  custom_lint: ^0.7.5
  flutter_lints: any
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  very_good_analysis: any
environment:
  flutter: '>=1.17.0'
  sdk: ^3.0.0
homepage: https://github.com/normidar/app_info_tile
name: app_info_tile
topics:
  - app-info
  - license
  - package-info
  - app
  - easy-localization
version: 0.0.1
